package user_interface;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.AbstractListModel;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.border.BevelBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class ConnectionPanel extends JPanel {

    // Variables declaration - do not modify                     
    private JLabel accessCountLabel;
    private JLabel accessGroupNameLabel;
    private JScrollPane accessPeosonLabel;
    private JLabel jLabel1;
    private JList<String> jList1;
    private JButton receiveButton;
    private JLabel sharedContentsInfoLabel;
    private JLabel sharedTimeLabel;
    // End of variables declaration   
	
    /**
     * Creates new form ConnectionPanel
     */
    public ConnectionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        accessPeosonLabel = new JScrollPane();
        jList1 = new JList<>();
        accessCountLabel = new JLabel();
        accessGroupNameLabel = new JLabel();
        sharedTimeLabel = new JLabel();
        sharedContentsInfoLabel = new JLabel();
        receiveButton = new JButton();
        jLabel1 = new JLabel();

        setLayout(new BorderLayout());

        this.setPreferredSize(new Dimension(300, 320));

        jList1.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        jList1.setModel(new AbstractListModel<String>() {
            String[] strings = { "student_1", "student_2", "delf", "heeeee", "doooy", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        accessPeosonLabel.setViewportView(jList1);

        accessCountLabel.setText("현재 5명 접속 중");

        accessGroupNameLabel.setText("Goddesses");

        sharedTimeLabel.setText("[2016-08-28 오후 2:51]");

        sharedContentsInfoLabel.setText("delf님이 \"테스트 문장을 복사하였습... \" 공유");

        receiveButton.setText("Receive");
        receiveButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                receiveButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        GroupLayout thisLayout = new GroupLayout(this);
        this.setLayout(thisLayout);
        thisLayout.setHorizontalGroup(
            thisLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(thisLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(thisLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(thisLayout.createSequentialGroup()
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sharedTimeLabel))
                    .addGroup(thisLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                        .addGroup(GroupLayout.Alignment.LEADING, thisLayout.createSequentialGroup()
                            .addComponent(accessGroupNameLabel)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accessCountLabel))
                        .addGroup(GroupLayout.Alignment.LEADING, thisLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(accessPeosonLabel, GroupLayout.PREFERRED_SIZE, 240, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sharedContentsInfoLabel))
                        .addComponent(receiveButton, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        thisLayout.setVerticalGroup(
            thisLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(thisLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(thisLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(accessCountLabel)
                    .addComponent(accessGroupNameLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accessPeosonLabel, GroupLayout.PREFERRED_SIZE, 151, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(thisLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sharedTimeLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sharedContentsInfoLabel)
                .addGap(18, 18, 18)
                .addComponent(receiveButton)
                .addGap(24, 24, 24))
        );

        add(this, BorderLayout.CENTER);
        this.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>                        

    private void receiveButtonActionPerformed(ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             


                
}
