package user_interface;

import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class ConnectionPanel extends JPanel {

    // Variables declaration - do not modify                     
    private JLabel accessCountLabel;
    private JLabel accessGroupNameLabel;
    private javax.swing.JScrollPane accessPeosonLabel;
    private javax.swing.JPanel connectionPanel;
    private JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JButton receiveButton;
    private JLabel sharedContentsInfoLabel;
    private JLabel sharedTimeLabel;
    // End of variables declaration   
	
    /**
     * Creates new form ConnectionPanel
     */
    public ConnectionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        connectionPanel = new javax.swing.JPanel();
        accessPeosonLabel = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        accessCountLabel = new JLabel();
        accessGroupNameLabel = new JLabel();
        sharedTimeLabel = new JLabel();
        sharedContentsInfoLabel = new JLabel();
        receiveButton = new javax.swing.JButton();
        jLabel1 = new JLabel();

        setLayout(new java.awt.BorderLayout());

        connectionPanel.setPreferredSize(new java.awt.Dimension(300, 320));

        jList1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "student_1", "student_2", "delf", "heeeee", "doooy", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        accessPeosonLabel.setViewportView(jList1);

        accessCountLabel.setText("현재 5명 접속 중");

        accessGroupNameLabel.setText("Goddesses");

        sharedTimeLabel.setText("[2016-08-28 오후 2:51]");

        sharedContentsInfoLabel.setText("delf님이 \"테스트 문장을 복사하였습... \" 공유");

        receiveButton.setText("Receive");
        receiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout connectionPanelLayout = new javax.swing.GroupLayout(connectionPanel);
        connectionPanel.setLayout(connectionPanelLayout);
        connectionPanelLayout.setHorizontalGroup(
            connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectionPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(connectionPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sharedTimeLabel))
                    .addGroup(connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, connectionPanelLayout.createSequentialGroup()
                            .addComponent(accessGroupNameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accessCountLabel))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accessPeosonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sharedContentsInfoLabel))
                        .addComponent(receiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        connectionPanelLayout.setVerticalGroup(
            connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectionPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accessCountLabel)
                    .addComponent(accessGroupNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accessPeosonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sharedTimeLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sharedContentsInfoLabel)
                .addGap(18, 18, 18)
                .addComponent(receiveButton)
                .addGap(24, 24, 24))
        );

        add(connectionPanel, java.awt.BorderLayout.CENTER);
        connectionPanel.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>                        

    private void receiveButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             


                
}
