package user_interface;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.AbstractListModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class HistoryPanel extends JPanel {

    // Variables declaration - do not modify                     
    private JPanel historyPanel;
    private JList<String> jList3;
    private JButton receiveButton2;
    private JScrollPane userHistoryList;
    // End of variables declaration  
	
    /**
     * Creates new form HistoryPanel
     */
    public HistoryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        userHistoryList = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        receiveButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        this.setPreferredSize(new Dimension(300, 320));

        jList3.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        userHistoryList.setViewportView(jList3);

        receiveButton2.setText("Receive");
        receiveButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                receiveButton2ActionPerformed(evt);
            }
        });

        GroupLayout historyPanelLayout = new GroupLayout(historyPanel);
        this.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userHistoryList)
                .addContainerGap())
            .addGroup(GroupLayout.Alignment.TRAILING, historyPanelLayout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(receiveButton2, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, historyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userHistoryList, GroupLayout.PREFERRED_SIZE, 265, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(receiveButton2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        add(this, BorderLayout.CENTER);
    }// </editor-fold>                        

    private void receiveButton2ActionPerformed(ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              
}
