package user_interface;

import java.awt.BorderLayout;
import java.awt.Container;

import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class UserInterfaceManager extends JFrame {

	private UserInterfacePage1 page1 = new UserInterfacePage1();
	
	Container contentPane;
	
	private static final int startXOfFrame = 0;
	private static final int startYOfFrame = 0;
	private static final int endXOfFrame = 336;
	private static final int endYOfFrame = 439;
	private static final int endXOfPanel = 320;
	private static final int endYOfPanel = 400;
	
	private static final int buttonWidth = 80;
	private static final int buttonHeight = 23;
	
	public UserInterfaceManager() {
		setTitle("LinKlipboard");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setSize(endXOfFrame, endYOfFrame);
		
		contentPane = getContentPane();
		//contentPane.setLayout(null);
		//contentPane.setLayout(new GroupLayout(this));

		contentPane.add(page1);

		setVisible(true);
		//setResizable(false);
	}
	
	public static void main(String[] args) {
		new UserInterfaceManager();
	}
	
//
//	/**
//	 * Creates new form UserInterfaceManager
//	 */
//	public UserInterfaceManager() {
//		initComponents();
//	}
//
//	/**
//	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
//	 */
//	@SuppressWarnings("unchecked")
//	// <editor-fold defaultstate="collapsed" desc="Generated Code">
//	private void initComponents() {
//
//		page1 = new UserInterfacePage1();
//
//		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
//
//		GroupLayout jPanel1Layout = new GroupLayout(page1);
//		page1.setLayout(jPanel1Layout);
//
//		GroupLayout layout = new GroupLayout(getContentPane());
//		getContentPane().setLayout(layout);
//		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(page1,
//				GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
//		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(page1,
//				GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
//
//		pack();
//	}// </editor-fold>
//
//	public static void main(String args[]) {
//		try {
//			for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
//				if ("Nimbus".equals(info.getName())) {
//					UIManager.setLookAndFeel(info.getClassName());
//					break;
//				}
//			}
//		} catch (ClassNotFoundException ex) {
//			Logger.getLogger(UserInterfaceManager.class.getName()).log(Level.SEVERE, null, ex);
//		} catch (InstantiationException ex) {
//			Logger.getLogger(UserInterfaceManager.class.getName()).log(Level.SEVERE, null, ex);
//		} catch (IllegalAccessException ex) {
//			Logger.getLogger(UserInterfaceManager.class.getName()).log(Level.SEVERE, null, ex);
//		} catch (UnsupportedLookAndFeelException ex) {
//			Logger.getLogger(UserInterfaceManager.class.getName()).log(Level.SEVERE, null, ex);
//		}
//		// </editor-fold>
//
//		/* Create and display the form */
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new UserInterfaceManager().setVisible(true);
//			}
//		});
//	}

}
